# Generated by Django 4.2.1 on 2023-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0005_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('degree', 'Degree'), ('master', 'Master'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
